# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_datefields_notblank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name=b'date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
