# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deleted_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
