# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-17 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='post',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='scheduled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usericon',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_icon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
