# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-01-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_worklog_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloglabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='api.Label'),
        ),
        migrations.AlterField(
            model_name='workloglabel',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.WorkLog'),
        ),
    ]
