# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-01-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_related_names_workloglabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workloglabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='workloglabel',
            name='log',
        ),
        migrations.AddField(
            model_name='worklog',
            name='labels',
            field=models.ManyToManyField(to='api.Label'),
        ),
        migrations.DeleteModel(
            name='WorkLogLabel',
        ),
    ]
