# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_manytomany_workloglabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.LabelGroup'),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='labelgroup',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
