# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_label_group_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='api.LabelGroup'),
        ),
    ]
