# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-02-22 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_removed_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelgroup',
            name='single',
        ),
        migrations.AddField(
            model_name='labelgroup',
            name='color',
            field=models.CharField(default=b'#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='worklog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
