# Generated by Django 3.2.8 on 2021-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_worklog_and_label_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
