# Generated by Django 3.2.13 on 2023-04-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_worklog_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Pln'), ('EUR', 'Eur')], default='PLN', max_length=3),
        ),
    ]
