# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170806_2102'),
    ]

    # TODO: Add sqlparse to requrements
    operations = [
        # Replaced DATETIME(6) with DATETIME
        # Milliseconds are not needed and consume db resources
        migrations.RunSQL('ALTER TABLE blog_post MODIFY date DATETIME;')
    ]
